### ISSUE TITLE
Dadaset Issues

### ISSUE THREAD

**Issue by asdddsdf** [Correr-Zhou/RepMode#2]

**Comment by Correr-Zhou** [comment]
Hi there,

If you still need any other download links of the formatted data, please feel free to let me know. : )

Donghao Zhou

**Comment by asdddsdf** [comment]
Hello,          Perhaps my previous email was overlooked, so I'll send it again. In your RepMode project, I forked the project and found that the download speed for the dataset on the server is very slow, only around tens of Kbps. I also noticed that there are formatted data (i.e., the .pth files) available for download, but the link doesn't work. Could you possibly share the dataset and the formatted data via Baidu Drive or another cloud storage service? Thank you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Correr-Zhou/RepMode"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 晚上9:10
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [Correr-Zhou/RepMode] Dadaset Issues (Issue #2)





 
Hi there,
 
If you still need any other download links of the formatted data, please feel free to let me know. : )
 
Donghao Zhou

**Comment by Correr-Zhou** [comment]
The download link of the formatted data works well here. You can try accessing it via VPN. 
As the original and formatted data are too large, other cloud-based storage services may not be suitable.
