### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [Correr-Zhou/RepMode#3]
Dear Authors,

How long does your method need to train? How to obtain the cell image shown in this paper?

Thanks

**Comment by Correr-Zhou** [comment]
Hi AmingWu,

Sorry for my late reply.

1. It generally requires ~30h on a V100 GPU. It can be faster if you run it with better GPUs or distributed training.
2. You can follow the instructions in README.md to download the source data, or directly download the formatted data [here](https://onedrive.live.com/?authkey=%21AAhW3Cc787v4s5M&id=9936AB911656DCB5%21362484&cid=9936AB911656DCB5).

Do let me know if you have any other questions. : )

Donghao Zhou

**Comment by AmingWu** [comment]
OK, Thanks very much. Could you tell me whether the dataset could be shown in image format?

**Comment by Correr-Zhou** [comment]
Yes. You can visualize it with professional software (e.g., ImageJ or Imaris).
You can also transfer it to a common image format (e.g., jpg, png) with python code.

**Comment by AmingWu** [comment]
Thank you.

**Comment by Correr-Zhou** [comment]
You're welcome. Open another issue if you have any other questions. : )
