### ISSUE TITLE
Data Issue

### ISSUE THREAD

**Issue by AmingWu** [Correr-Zhou/RepMode#4]
Dear Authors,

I find the data size is [1, 50, 232, 344]. Is the channel number 50? Could you give the visual code to visualize the data with 50 channels?

Thanks

**Comment by Correr-Zhou** [comment]
Actually, it is the dimension for the z-axis.
For visualization, I recommend using off-the-shelf tools (e.g., ImageJ, Imaris) which we use in our project.
